name: Build Zebra

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GIT_TOKEN }}

    - name: Install Theos Dependencies
      run: brew install make cmake gettext gnutls lz4 zstd libgcrypt libgpg-error xxhash

    - name: Install ldid
      run: |
        curl -Lo /usr/local/bin/ldid https://github.com/ProcursusTeam/ldid/releases/latest/download/ldid_macosx_arm64
        chmod +x /usr/local/bin/ldid

    - name: Install Theos
      uses: actions/checkout@v4
      with:
        repository: theos/theos
        path: theos
        submodules: recursive

    - name: Build libapt
      run: Vendor/Plains/Vendor/build-libapt.sh

    - name: Build Package
      env:
        THEOS: theos
        FAKEROOT: sudo
      run: gmake package

    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: Zebra.deb
        path: packages/*.deb
        if-no-files-found: error
